"""migration

Revision ID: 475d38ce02e7
Revises: 55caa2bbc778
Create Date: 2023-10-25 20:51:58.589805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '475d38ce02e7'
down_revision = '55caa2bbc778'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_column('email')

    # ### end Alembic commands ###
