"""Initial migration.

Revision ID: 55caa2bbc778
Revises: 
Create Date: 2023-10-25 20:50:37.252805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55caa2bbc778'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_name'))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
